name: Export

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

env:
  GameName: RobotVsRobots
  BuilVersion: "0.${{ github.run_number}}.0"

jobs:
  build-export:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Godot
        run: |
          Invoke-WebRequest "https://github.com/godotengine/godot-builds/releases/download/4.3-dev6/Godot_v4.3-dev6_win64.exe.zip" -OutFile godot.zip
          Expand-Archive .\godot.zip
          & .\godot\Godot_v4.3-dev6_win64_console.exe --version
          
          Invoke-WebRequest "https://github.com/godotengine/godot-builds/releases/download/4.3-dev6/Godot_v4.3-dev6_export_templates.tpz" -OutFile templates.zip
          Expand-Archive .\templates.zip C:/Users/runneradmin/AppData/Roaming/Godot/export_templates/
          Rename-Item C:/Users/runneradmin/AppData/Roaming/Godot/export_templates/templates 4.3.dev6
          ls -r C:/Users/runneradmin/AppData/Roaming/Godot/export_templates

          Invoke-WebRequest "https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe" -OutFile C:/Users/runneradmin/AppData/Roaming/Godot/rcedit.exe
          & .\godot\Godot_v4.3-dev6_win64_console.exe -v -e --quit --headless
          $configFile = "C:/Users/runneradmin/AppData/Roaming/Godot/editor_settings-4.3.tres"
          (Get-Content $configFile) -replace 'export/windows/rcedit = ""', 'export/windows/rcedit = "C:/Users/runneradmin/AppData/Roaming/Godot/rcedit.exe"' | Set-Content $configFile

      - name: Build Windows
        run: |
          mkdir .\build\windows
          & .\godot\Godot_v4.3-dev6_win64_console.exe --headless --verbose --export-release "Windows Desktop" .\build\windows\${{ env.GameName }}.exe

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GameName }}-Windows
          path: build/windows

      - name: Build Web
        run: |
          mkdir .\build\web
          & .\godot\Godot_v4.3-dev6_win64_console.exe --headless --verbose --export-release "Web" .\build\web\index.html

      - name: Upload Web for github pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ env.GameName }}-Web
          path: build/web

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ env.GameName }}-Web

      - name: Compress for Release
        run: |
          Compress-Archive -Path .\build\web -DestinationPath .\${{ env.GameName }}-Web.zip

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.BuilVersion }}
          artifacts: "./build/windows/${{ env.GameName }}.exe,${{ env.GameName }}-Web.zip"